from typing import Dict, List, Optional
import requests
import json
import logging
from datetime import datetime
from django.conf import settings
from ..models import Server, ServerStatus

logger = logging.getLogger(__name__)

class PanelManager:
    """
    Service class for managing interactions with 3x-ui panels
    """
    def __init__(self, server: Server):
        self.server = server
        self.session = requests.Session()
        self.base_url = f"http://{server.ip_address}:{server.port}"
        self.api_path = server.panel_path
        self.is_authenticated = False
        
    def _build_url(self, endpoint: str) -> str:
        """Build full URL for API endpoint"""
        return f"{self.base_url}{self.api_path}{endpoint}"
    
    def authenticate(self) -> bool:
        """
        Authenticate with the panel and store session cookies
        """
        try:
            login_url = self._build_url("/login")
            data = {
                "username": self.server.username,
                "password": self.server.password
            }
            
            response = self.session.post(login_url, json=data)
            response.raise_for_status()
            
            if response.json().get("success"):
                self.is_authenticated = True
                logger.info(f"Successfully authenticated with panel on server {self.server.name}")
                return True
                
            logger.error(f"Authentication failed for server {self.server.name}")
            return False
            
        except Exception as e:
            logger.error(f"Error authenticating with panel: {str(e)}")
            return False
    
    def _ensure_authenticated(self):
        """Ensure we have an active session"""
        if not self.is_authenticated:
            self.authenticate()
    
    def get_system_status(self) -> Optional[Dict]:
        """
        Get system status including CPU, RAM, and network usage
        """
        self._ensure_authenticated()
        try:
            status_url = self._build_url("/status")
            response = self.session.get(status_url)
            response.raise_for_status()
            
            data = response.json()
            
            # Save status to database
            ServerStatus.objects.create(
                server=self.server,
                cpu_usage=data.get("cpu", 0),
                memory_usage=data.get("memory", 0),
                disk_usage=data.get("disk", 0),
                network_in=data.get("network", {}).get("in", 0),
                network_out=data.get("network", {}).get("out", 0),
                timestamp=datetime.now()
            )
            
            return data
            
        except Exception as e:
            logger.error(f"Error getting system status: {str(e)}")
            return None
    
    def create_client(self, email: str, traffic_limit: int = 0, expire_days: int = 30) -> Optional[Dict]:
        """
        Create a new client account
        
        Args:
            email: Client email/username
            traffic_limit: Traffic limit in GB (0 for unlimited)
            expire_days: Number of days until expiration
        """
        self._ensure_authenticated()
        try:
            create_url = self._build_url("/inbound/add")
            data = {
                "email": email,
                "traffic_limit": traffic_limit * 1024 * 1024 * 1024,  # Convert to bytes
                "expire_days": expire_days,
                "protocol": "vmess",  # Can be made configurable
                "settings": {
                    "clients": [{
                        "email": email,
                        "id": "",  # Will be generated by panel
                        "alterId": 0
                    }]
                }
            }
            
            response = self.session.post(create_url, json=data)
            response.raise_for_status()
            
            return response.json()
            
        except Exception as e:
            logger.error(f"Error creating client: {str(e)}")
            return None
    
    def get_client_traffic(self, email: str) -> Optional[Dict]:
        """Get traffic usage for a specific client"""
        self._ensure_authenticated()
        try:
            traffic_url = self._build_url(f"/inbound/traffic/{email}")
            response = self.session.get(traffic_url)
            response.raise_for_status()
            
            return response.json()
            
        except Exception as e:
            logger.error(f"Error getting client traffic: {str(e)}")
            return None
    
    def delete_client(self, email: str) -> bool:
        """Delete a client account"""
        self._ensure_authenticated()
        try:
            delete_url = self._build_url(f"/inbound/del/{email}")
            response = self.session.delete(delete_url)
            response.raise_for_status()
            
            return response.json().get("success", False)
            
        except Exception as e:
            logger.error(f"Error deleting client: {str(e)}")
            return False
    
    def get_all_clients(self) -> Optional[List[Dict]]:
        """Get list of all clients and their status"""
        self._ensure_authenticated()
        try:
            clients_url = self._build_url("/inbound/list")
            response = self.session.get(clients_url)
            response.raise_for_status()
            
            return response.json()
            
        except Exception as e:
            logger.error(f"Error getting client list: {str(e)}")
            return None
    
    def update_client(self, email: str, **kwargs) -> bool:
        """
        Update client settings
        
        Args:
            email: Client email/username
            **kwargs: Settings to update (traffic_limit, expire_days, etc.)
        """
        self._ensure_authenticated()
        try:
            update_url = self._build_url(f"/inbound/update/{email}")
            response = self.session.put(update_url, json=kwargs)
            response.raise_for_status()
            
            return response.json().get("success", False)
            
        except Exception as e:
            logger.error(f"Error updating client: {str(e)}")
            return False
    
    def reset_traffic(self, email: str) -> bool:
        """Reset traffic statistics for a client"""
        self._ensure_authenticated()
        try:
            reset_url = self._build_url(f"/inbound/resetTraffic/{email}")
            response = self.session.post(reset_url)
            response.raise_for_status()
            
            return response.json().get("success", False)
            
        except Exception as e:
            logger.error(f"Error resetting client traffic: {str(e)}")
            return False 