version: '3.8'

services:
  pgadmin:
    container_name: moonvpn_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moonvpn.ir
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - moonvpn-network

networks:
  moonvpn-network:
    external: true

volumes:
  pgadmin-data: 