"""add_fields_to_inbound

Revision ID: 724ae4596ec7
Revises: 5ec2e2e0d2ca
Create Date: 2025-04-23 02:01:48.138684+03:30

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '724ae4596ec7'
down_revision = '5ec2e2e0d2ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound', sa.Column('listen', sa.String(length=100), nullable=True))
    op.add_column('inbound', sa.Column('stream_settings', sa.JSON(), nullable=True))
    op.add_column('inbound', sa.Column('allocate_settings', sa.JSON(), nullable=True))
    op.add_column('inbound', sa.Column('receive_original_dest', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('inbound', sa.Column('allow_transparent', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('inbound', sa.Column('security_settings', sa.JSON(), nullable=True))
    op.add_column('inbound', sa.Column('remark', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound', 'remark')
    op.drop_column('inbound', 'security_settings')
    op.drop_column('inbound', 'allow_transparent')
    op.drop_column('inbound', 'receive_original_dest')
    op.drop_column('inbound', 'allocate_settings')
    op.drop_column('inbound', 'stream_settings')
    op.drop_column('inbound', 'listen')
    # ### end Alembic commands ### 