"""change panel status to enum

Revision ID: bafc9dbe1132
Revises: bafc9dbe1131
Create Date: 2025-04-21 00:12:34.123456+03:30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import Enum


# revision identifiers, used by Alembic.
revision = 'bafc9dbe1132'
down_revision = 'bafc9dbe1131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create temporary column
    op.add_column('panels', sa.Column('status_new', 
                  sa.Enum('active', 'disabled', 'deleted', name='panelstatus'),
                  nullable=False,
                  server_default='active'))
    
    # Update the new column based on old boolean value
    op.execute("""
        UPDATE panels 
        SET status_new = CASE 
            WHEN status = 1 THEN 'active' 
            ELSE 'disabled' 
        END
    """)
    
    # Drop old column and rename new one
    op.drop_column('panels', 'status')
    op.alter_column('panels', 'status_new',
                    new_column_name='status',
                    existing_type=sa.Enum('active', 'disabled', 'deleted', name='panelstatus'),
                    nullable=False,
                    server_default='active')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create temporary boolean column
    op.add_column('panels', sa.Column('status_old', sa.Boolean(), 
                  nullable=False, 
                  server_default='1'))
    
    # Update the boolean column based on enum value
    op.execute("""
        UPDATE panels 
        SET status_old = CASE 
            WHEN status = 'active' THEN 1 
            ELSE 0 
        END
    """)
    
    # Drop enum column and rename boolean one
    op.drop_column('panels', 'status')
    op.alter_column('panels', 'status_old',
                    new_column_name='status',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default='1')
    
    # Drop the enum type
    op.execute('DROP TYPE panelstatus')
    # ### end Alembic commands ### 