"""fix inbound client accounts relationship

Revision ID: bafc9dbe1133
Revises: bafc9dbe1132
Create Date: 2025-04-21 00:12:35.123456+03:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc9dbe1133'
down_revision = 'bafc9dbe1132'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key if it exists
    op.drop_constraint('fk_client_accounts_inbound_id_inbounds', 'client_accounts', type_='foreignkey')
    
    # Add the correct foreign key constraint
    op.create_foreign_key(
        'fk_client_accounts_inbound',
        'client_accounts',
        'inbound',
        ['inbound_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the new foreign key constraint
    op.drop_constraint('fk_client_accounts_inbound', 'client_accounts', type_='foreignkey')
    
    # Restore the original foreign key
    op.create_foreign_key(
        'fk_client_accounts_inbound_id_inbounds',
        'client_accounts',
        'inbound',
        ['inbound_id'],
        ['id']
    )
    
    # ### end Alembic commands ###