"""add payment_method to transactions

Revision ID: 20250502_043846
Revises: 20250501_update_panel_status
Create Date: 2025-05-02 04:38:46.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20250502_043846'
down_revision: Union[str, None] = '20250501_update_panel_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.Enum('WALLET', 'CARD', 'ONLINE', name='paymentmethod'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###