"""sdf

Revision ID: bafc9dbe1130
Revises: 22f1274a8a5b
Create Date: 2025-04-20 03:10:42.292789+03:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc9dbe1130'
down_revision = '22f1274a8a5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 