"""create_all_tables_fixed

Revision ID: 22f1274a8a5b
Revises: f9d119ba246c
Create Date: 2025-04-19 23:20:28.304949+03:30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22f1274a8a5b'
down_revision = 'f9d119ba246c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('transfer_id', sa.String(length=100), nullable=False),
    sa.Column('transfer_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('traffic_total', sa.Integer(), nullable=False),
    sa.Column('traffic_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DISABLED', name='accountstatus'), nullable=False),
    sa.Column('config_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inbound_id'], ['inbounds.id'], name=op.f('fk_client_accounts_inbound_id_inbounds')),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], name=op.f('fk_client_accounts_panel_id_panels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_accounts')),
    sa.UniqueConstraint('transfer_id', name=op.f('uq_client_accounts_transfer_id'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'PURCHASE', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_transactions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_table('account_transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_account_id', sa.Integer(), nullable=False),
    sa.Column('new_account_id', sa.Integer(), nullable=False),
    sa.Column('from_panel_id', sa.Integer(), nullable=False),
    sa.Column('to_panel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_panel_id'], ['panels.id'], name=op.f('fk_account_transfer_from_panel_id_panels')),
    sa.ForeignKeyConstraint(['new_account_id'], ['client_accounts.id'], name=op.f('fk_account_transfer_new_account_id_client_accounts')),
    sa.ForeignKeyConstraint(['old_account_id'], ['client_accounts.id'], name=op.f('fk_account_transfer_old_account_id_client_accounts')),
    sa.ForeignKeyConstraint(['to_panel_id'], ['panels.id'], name=op.f('fk_account_transfer_to_panel_id_panels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_transfer'))
    )
    op.alter_column('users', 'balance',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_table('account_transfer')
    op.drop_table('transactions')
    op.drop_table('client_accounts')
    # ### end Alembic commands ### 