"""add_created_at_to_plans

Revision ID: 5ec2e2e0d2ca
Revises: 4e600331fdbc
Create Date: 2025-04-22 15:44:47.557598+03:30

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ec2e2e0d2ca'
down_revision = '4e600331fdbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='زمان ایجاد'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'created_at')
    # ### end Alembic commands ### 