"""fix panel inbound clientaccount models

Revision ID: 80a5b003f34b
Revises: 5821b73312a3
Create Date: 2025-04-27 01:59:05.760240+03:30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80a5b003f34b'
down_revision = '5821b73312a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the flag_emoji column to panels table as it's missing
    op.add_column('panels', sa.Column('flag_emoji', sa.String(length=10), nullable=True))
    
    # Update panel status enum
    op.alter_column('panels', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'DISABLED', 'INACTIVE', 'DELETED'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='panelstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert panel status enum
    op.alter_column('panels', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='panelstatus'),
               type_=mysql.ENUM('ACTIVE', 'DISABLED', 'INACTIVE', 'DELETED'),
               existing_nullable=False)
    
    # Drop flag_emoji column
    op.drop_column('panels', 'flag_emoji')
    # ### end Alembic commands ### 