"""add PENDING_RECEIPT status to OrderStatus enum

Revision ID: 5f6b84a12d7e
Revises: 80a5b003f34b
Create Date: 2025-04-27 08:30:00.000000+03:30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f6b84a12d7e'
down_revision = '80a5b003f34b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modify the OrderStatus enum to include PENDING_RECEIPT
    op.execute("ALTER TABLE orders MODIFY COLUMN status ENUM('PENDING', 'PAID', 'COMPLETED', 'FAILED', 'EXPIRED', 'PENDING_RECEIPT') NOT NULL DEFAULT 'PENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove PENDING_RECEIPT from OrderStatus enum
    op.execute("ALTER TABLE orders MODIFY COLUMN status ENUM('PENDING', 'PAID', 'COMPLETED', 'FAILED', 'EXPIRED') NOT NULL DEFAULT 'PENDING'")
    # ### end Alembic commands ### 