"""update inbound table with new columns

Revision ID: bafc9dbe1131
Revises: bafc9dbe1130
Create Date: 2025-04-20 03:10:43.292789+03:30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'bafc9dbe1131'
down_revision = 'bafc9dbe1130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('inbounds', 'inbound')
    
    # Rename inbound_id to remote_id
    op.alter_column('inbound', 'inbound_id',
                    new_column_name='remote_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    
    # Add new columns
    op.add_column('inbound', sa.Column('port', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('inbound', sa.Column('settings_json', sa.JSON(), nullable=True))
    op.add_column('inbound', sa.Column('sniffing', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('inbound', sa.Column('status', sa.String(20), nullable=False, server_default='active'))
    op.add_column('inbound', sa.Column('max_clients', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('inbound', sa.Column('last_synced', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    
    # Drop old columns
    op.drop_column('inbound', 'client_limit')
    op.drop_column('inbound', 'traffic_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old columns
    op.add_column('inbound', sa.Column('client_limit', sa.Integer(), nullable=False))
    op.add_column('inbound', sa.Column('traffic_limit', sa.Integer(), nullable=True))
    
    # Drop new columns
    op.drop_column('inbound', 'last_synced')
    op.drop_column('inbound', 'max_clients')
    op.drop_column('inbound', 'status')
    op.drop_column('inbound', 'sniffing')
    op.drop_column('inbound', 'settings_json')
    op.drop_column('inbound', 'port')
    
    # Rename remote_id back to inbound_id
    op.alter_column('inbound', 'remote_id',
                    new_column_name='inbound_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    
    op.rename_table('inbound', 'inbounds')
    # ### end Alembic commands ### 