"""update client accounts inbound fk

Revision ID: bafc9dbe1134
Revises: bafc9dbe1133
Create Date: 2025-04-21 00:12:36.123456+03:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc9dbe1134'
down_revision = 'bafc9dbe1133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key
    op.drop_constraint('fk_client_accounts_inbound', 'client_accounts', type_='foreignkey')
    
    # Add the new foreign key with CASCADE
    op.create_foreign_key(
        'fk_client_accounts_inbound',
        'client_accounts',
        'inbound',
        ['inbound_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the CASCADE foreign key
    op.drop_constraint('fk_client_accounts_inbound', 'client_accounts', type_='foreignkey')
    
    # Restore the original foreign key without CASCADE
    op.create_foreign_key(
        'fk_client_accounts_inbound',
        'client_accounts',
        'inbound',
        ['inbound_id'],
        ['id']
    )
    
    # ### end Alembic commands ### 