"""add is_active to plans

Revision ID: bafc9dbe1135
Revises: bafc9dbe1134
Create Date: 2025-04-21 00:12:37.123456+03:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc9dbe1135'
down_revision = 'bafc9dbe1134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add is_active column with default True
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    
    # Create index for faster queries
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop index first
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    
    # Then drop column
    op.drop_column('plans', 'is_active')
    
    # ### end Alembic commands ### 