"""add_admin_permissions_table_and_relation_to_user_fix_unique_constraint

Revision ID: 394eae8c93d8
Revises: add_payment_settings
Create Date: 2025-04-28 07:52:53.832414+03:30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '394eae8c93d8'
down_revision = 'add_payment_settings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('can_approve_receipt', sa.Boolean(), nullable=False),
    sa.Column('can_support', sa.Boolean(), nullable=False),
    sa.Column('can_view_users', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_permissions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_permissions')),
    sa.UniqueConstraint('user_id', name='uq_admin_permissions_user_id')
    )
    op.drop_index('ix_wallets_user_id', table_name='wallets')
    op.drop_table('wallets')
    op.create_foreign_key(op.f('fk_discount_codes_user_id_users'), 'discount_codes', 'users', ['user_id'], ['id'])
    op.drop_column('discount_codes', 'start_date')
    op.drop_column('discount_codes', 'value')
    op.drop_column('discount_codes', 'max_discount')
    op.drop_column('discount_codes', 'end_date')
    op.drop_column('discount_codes', 'active')
    op.drop_column('discount_codes', 'usage_limit')
    op.drop_column('discount_codes', 'used_count')
    op.drop_column('discount_codes', 'min_order')
    op.drop_column('discount_codes', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_permissions')
    # ### end Alembic commands ### 