from setuptools import setup, find_packages

setup(
    name="moonvpn",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "python-telegram-bot>=20.0",
        "psycopg2-binary>=2.9.5",
        "asyncpg>=0.27.0",
        "aiohttp>=3.8.4",
        "python-dotenv>=1.0.0",
        "pydantic>=2.0.0",
        "jdatetime>=4.1.0",
        "redis>=4.5.4",
        "pillow>=9.5.0",
        "qrcode>=7.4.2",
        "requests>=2.28.2",
        "zeep>=4.2.1",
        "cryptography>=40.0.2",
        "pytz>=2023.3",
        "schedule>=1.2.0",
        "colorama>=0.4.6",
        "click>=8.1.3",
        "tabulate>=0.9.0",
        "tqdm>=4.65.0",
        "humanize>=4.6.0",
        "psutil>=5.9.5",
        "pyfiglet>=0.8.post1",
        "rich>=13.3.5",
        "typer>=0.9.0",
        "fastapi>=0.95.1",
        "uvicorn>=0.22.0",
        "websockets>=11.0.3",
        "aiogram>=3.0.0",
        "aiofiles>=23.1.0",
        "aioredis>=2.0.1",
        "aiocache>=0.12.1",
        "aiodns>=3.0.0",
        "aiosignal>=1.3.1",
        "aiosmtplib>=2.0.1",
        "aiosqlite>=0.19.0",
        "aiologger>=0.7.0",
    ],
    entry_points={
        "console_scripts": [
            "moonvpn=bot.cli.main:cli",
        ],
    },
    author="MoonVPN Team",
    author_email="info@example.com",
    description="Telegram bot and dashboard for V2Ray management",
    keywords="vpn, v2ray, telegram, bot, dashboard",
    url="https://github.com/k4lantar4/moonvpn",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: System :: Systems Administration",
    ],
    python_requires=">=3.10",
) 