"""Add Wallet model and move balance from User

Revision ID: 2268f7a04299
Revises: 3909e27c74fc
Create Date: 2025-04-10 12:12:54.574676+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2268f7a04299'
down_revision = '3909e27c74fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
