"""reflect schema changes after import fixes

Revision ID: 3909e27c74fc
Revises: 45b77c23b80e
Create Date: 2025-04-09 20:45:19.665707+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3909e27c74fc'
down_revision = '45b77c23b80e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_channels', sa.Column('event', sa.Enum('NEW_USER', 'PAYMENT_VERIFICATION', 'PAYMENT_COMPLETED', 'PANEL_DOWN', 'PANEL_RECOVERED', 'LOW_BALANCE', 'EXPIRY_WARNING', 'DB_BACKUP_SUCCESS', 'DB_BACKUP_FAILURE', 'CRITICAL_ERROR', 'SALES_REPORT', 'USAGE_REPORT', name='notificationevent'), nullable=False))
    op.alter_column('notification_channels', 'channel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'notification_channels', ['channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_channels', type_='unique')
    op.alter_column('notification_channels', 'channel_id',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_column('notification_channels', 'event')
    # ### end Alembic commands ###
