"""initial database schema

Revision ID: 45b77c23b80e
Revises: 
Create Date: 2025-04-09 19:59:40.211179+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b77c23b80e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rotation_priority', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('daily_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocols_supported', sa.String(length=100), nullable=True),
    sa.Column('inbound_tag_pattern', sa.String(length=100), nullable=True),
    sa.Column('default_remark_prefix', sa.String(length=50), nullable=True),
    sa.Column('remark_pattern', sa.String(length=255), nullable=True),
    sa.Column('migration_remark_pattern', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notification_types', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plan_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sorting_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'SELLER', 'USER', name='rolename'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('can_manage_panels', sa.Boolean(), nullable=True),
    sa.Column('can_manage_users', sa.Boolean(), nullable=True),
    sa.Column('can_manage_plans', sa.Boolean(), nullable=True),
    sa.Column('can_approve_payments', sa.Boolean(), nullable=True),
    sa.Column('can_broadcast', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('commission_percent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('client_id_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_id', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id_sequences_location_id'), 'client_id_sequences', ['location_id'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('traffic', sa.BigInteger(), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=True),
    sa.Column('protocols', sa.String(length=255), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sorting_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['plan_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('discount_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('FIXED', 'PERCENTAGE', name='discount_type_enum'), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('api_path', sa.String(length=100), nullable=True),
    sa.Column('login_path', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('panel_type', sa.Enum('XUI', 'MARZBAN', 'SANAEI', 'ALIREZA', 'VAXILU', 'XRAY', name='paneltype'), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('server_ip', sa.String(length=45), nullable=True),
    sa.Column('server_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('max_clients', sa.Integer(), nullable=True),
    sa.Column('current_clients', sa.Integer(), nullable=True),
    sa.Column('traffic_limit', sa.BigInteger(), nullable=True),
    sa.Column('traffic_used', sa.BigInteger(), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('api_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('geo_location', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('datacenter', sa.String(length=100), nullable=True),
    sa.Column('alternate_domain', sa.String(length=255), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('network_speed', sa.String(length=50), nullable=True),
    sa.Column('server_specs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', 'PURCHASE', 'REFUND', 'COMMISSION', name='transaction_type_enum'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('balance_after', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('discount_code_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='order_status_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_health_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_inbounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('inbound_id_panel', sa.Integer(), nullable=False, comment='ID of the inbound on the panel itself'),
    sa.Column('tag', sa.String(length=255), nullable=False, comment='Inbound tag name on the panel'),
    sa.Column('protocol', sa.String(length=50), nullable=False, comment='e.g., vmess, vless, trojan'),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('listen', sa.String(length=255), nullable=True, comment='Listen IP address'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='Raw settings JSON from the panel API'),
    sa.Column('stream_settings', sa.JSON(), nullable=True, comment='Raw stream settings JSON from the panel API'),
    sa.Column('total_gb', sa.BigInteger(), nullable=True, comment='Total traffic limit in bytes (from panel, 0 means unlimited)'),
    sa.Column('expiry_time', sa.BigInteger(), nullable=True, comment='Expiry timestamp (milliseconds) (from panel, 0 means no limit)'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Whether this inbound is active/enabled on the panel'),
    sa.Column('remark', sa.Text(), nullable=True, comment="Panel's description/remark for the inbound"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_inbounds_id'), 'panel_inbounds', ['id'], unique=False)
    op.create_index(op.f('ix_panel_inbounds_panel_id'), 'panel_inbounds', ['panel_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('panel_inbound_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.Column('traffic', sa.BigInteger(), nullable=False),
    sa.Column('used_traffic', sa.BigInteger(), nullable=True),
    sa.Column('subscription_url', sa.String(length=255), nullable=True),
    sa.Column('qrcode_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DISABLED', 'FROZEN', name='client_status_enum'), nullable=True),
    sa.Column('protocol', sa.Enum('VMESS', 'VLESS', 'TROJAN', 'SHADOWSOCKS', name='client_protocol_enum'), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('tls', sa.Boolean(), nullable=True),
    sa.Column('security', sa.String(length=20), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('freeze_start', sa.DateTime(), nullable=True),
    sa.Column('freeze_end', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('last_notified', sa.DateTime(), nullable=True),
    sa.Column('original_client_uuid', sa.String(length=36), nullable=True),
    sa.Column('original_remark', sa.String(length=255), nullable=True),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('migration_count', sa.Integer(), nullable=True),
    sa.Column('previous_panel_id', sa.Integer(), nullable=True),
    sa.Column('migration_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['panel_inbound_id'], ['panel_inbounds.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['previous_panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_gateway_id', sa.String(length=100), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('receipt_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='payment_status_enum'), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_migrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('from_panel_id', sa.Integer(), nullable=False),
    sa.Column('to_panel_id', sa.Integer(), nullable=False),
    sa.Column('old_client_uuid', sa.String(length=36), nullable=False),
    sa.Column('new_client_uuid', sa.String(length=36), nullable=False),
    sa.Column('old_remark', sa.String(length=255), nullable=False),
    sa.Column('new_remark', sa.String(length=255), nullable=False),
    sa.Column('traffic_remaining', sa.BigInteger(), nullable=False),
    sa.Column('time_remaining_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('migrated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['from_panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['to_panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_migrations')
    op.drop_table('payments')
    op.drop_table('clients')
    op.drop_index(op.f('ix_panel_inbounds_panel_id'), table_name='panel_inbounds')
    op.drop_index(op.f('ix_panel_inbounds_id'), table_name='panel_inbounds')
    op.drop_table('panel_inbounds')
    op.drop_table('panel_health_checks')
    op.drop_table('orders')
    op.drop_table('transactions')
    op.drop_table('panels')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_index(op.f('ix_client_id_sequences_location_id'), table_name='client_id_sequences')
    op.drop_table('client_id_sequences')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('plan_categories')
    op.drop_table('notification_channels')
    op.drop_table('locations')
    op.drop_table('bank_cards')
    # ### end Alembic commands ###
