"""--autogenerate -m Add inbound_id to ClientAccount model

Revision ID: 4996f1134b19
Revises: 4e61a3fdacab
Create Date: 2025-04-10 13:09:02.864568+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4996f1134b19'
down_revision = '4e61a3fdacab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('inbound_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_clients_inbound_id'), 'clients', ['inbound_id'], unique=False)
    op.drop_constraint('clients_ibfk_4', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'panel_inbounds', ['inbound_id'], ['id'])
    op.drop_column('clients', 'panel_inbound_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('panel_inbound_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_ibfk_4', 'clients', 'panel_inbounds', ['panel_inbound_id'], ['id'])
    op.drop_index(op.f('ix_clients_inbound_id'), table_name='clients')
    op.drop_column('clients', 'inbound_id')
    # ### end Alembic commands ###
