"""--autogenerate -m "Add panel_native_identifier to clients table"

Revision ID: 4e61a3fdacab
Revises: 2268f7a04299
Create Date: 2025-04-10 12:35:20.983732+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e61a3fdacab'
down_revision = '2268f7a04299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('panel_native_identifier', sa.String(length=255), nullable=True, comment='Identifier used by the panel API (e.g., email, uuid, password, internal ID)'))
    op.create_index(op.f('ix_clients_panel_native_identifier'), 'clients', ['panel_native_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_panel_native_identifier'), table_name='clients')
    op.drop_column('clients', 'panel_native_identifier')
    # ### end Alembic commands ###
