"""Fix model relationships

Revision ID: 95bc9a64bb26
Revises: 4f5a7b23e1c9
Create Date: 2025-04-08 02:52:24.919301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95bc9a64bb26'
down_revision = '4f5a7b23e1c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('client_migration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('max_migrations_per_day', sa.Integer(), nullable=True),
    sa.Column('allow_custom_remarks', sa.Integer(), nullable=True),
    sa.Column('remark_pattern', sa.String(length=100), nullable=True),
    sa.Column('migration_remark_pattern', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_index(op.f('ix_client_migration_settings_id'), 'client_migration_settings', ['id'], unique=False)
    op.create_table('panel_migration_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_panel_id', sa.Integer(), nullable=False),
    sa.Column('target_panel_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['target_panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_panel_id', 'target_panel_id')
    )
    op.create_index(op.f('ix_panel_migration_map_id'), 'panel_migration_map', ['id'], unique=False)
    op.drop_index('code', table_name='discount_codes')
    op.drop_table('discount_codes')
    op.alter_column('bank_cards', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_bank_cards_id'), 'bank_cards', ['id'], unique=False)
    op.create_index(op.f('ix_client_id_sequences_id'), 'client_id_sequences', ['id'], unique=False)
    op.add_column('client_migrations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('client_migrations', sa.Column('old_location_id', sa.Integer(), nullable=False))
    op.add_column('client_migrations', sa.Column('new_location_id', sa.Integer(), nullable=False))
    op.add_column('client_migrations', sa.Column('old_uuid', sa.String(length=36), nullable=False))
    op.add_column('client_migrations', sa.Column('new_uuid', sa.String(length=36), nullable=False))
    op.add_column('client_migrations', sa.Column('transferred_traffic', sa.BigInteger(), nullable=True))
    op.add_column('client_migrations', sa.Column('transferred_expiry', sa.Boolean(), nullable=True))
    op.add_column('client_migrations', sa.Column('performed_by', sa.Integer(), nullable=True))
    op.add_column('client_migrations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('client_migrations', 'reason',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_client_migrations_id'), 'client_migrations', ['id'], unique=False)
    op.create_foreign_key(None, 'client_migrations', 'users', ['performed_by'], ['id'])
    op.create_foreign_key(None, 'client_migrations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'client_migrations', 'locations', ['old_location_id'], ['id'])
    op.create_foreign_key(None, 'client_migrations', 'locations', ['new_location_id'], ['id'])
    op.drop_column('client_migrations', 'traffic_remaining')
    op.drop_column('client_migrations', 'time_remaining_days')
    op.drop_column('client_migrations', 'migrated_at')
    op.drop_column('client_migrations', 'notes')
    op.drop_column('client_migrations', 'new_client_uuid')
    op.drop_column('client_migrations', 'old_client_uuid')
    op.alter_column('clients', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'EXPIRED', 'DISABLED', 'FROZEN', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('clients', 'protocol',
               existing_type=mysql.ENUM('VMESS', 'VLESS', 'TROJAN', 'SHADOWSOCKS', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.drop_constraint('clients_ibfk_3', 'clients', type_='foreignkey')
    op.drop_constraint('clients_ibfk_7', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'panels', ['previous_panel_id'], ['id'])
    op.drop_column('clients', 'last_online')
    op.drop_column('clients', 'network')
    op.drop_column('clients', 'panel_inbound_id')
    op.drop_column('clients', 'security')
    op.drop_column('clients', 'tls')
    op.drop_column('clients', 'port')
    op.drop_column('clients', 'qrcode_url')
    op.add_column('locations', sa.Column('max_migrations_per_day', sa.Integer(), nullable=True))
    op.alter_column('locations', 'remark_pattern',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'{prefix}-{id}-{custom}'"))
    op.alter_column('locations', 'migration_remark_pattern',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'{original}-M{count}'"))
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_notification_channels_id'), 'notification_channels', ['id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=mysql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               nullable=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_panel_domains_id'), 'panel_domains', ['id'], unique=False)
    op.add_column('panel_health_checks', sa.Column('check_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('panel_health_checks', sa.Column('is_healthy', sa.Boolean(), nullable=False))
    op.add_column('panel_health_checks', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('panel_health_checks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('panel_health_checks', sa.Column('cpu_usage', sa.String(length=20), nullable=True))
    op.add_column('panel_health_checks', sa.Column('memory_usage', sa.String(length=20), nullable=True))
    op.add_column('panel_health_checks', sa.Column('disk_usage', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_panel_health_checks_id'), 'panel_health_checks', ['id'], unique=False)
    op.drop_column('panel_health_checks', 'details')
    op.drop_column('panel_health_checks', 'checked_at')
    op.drop_column('panel_health_checks', 'status')
    op.alter_column('panel_inbounds', 'tag',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('panel_inbounds', 'protocol',
               existing_type=mysql.ENUM('VMESS', 'VLESS', 'TROJAN', 'SHADOWSOCKS', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('panel_inbounds', 'port',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('panel_id', table_name='panel_inbounds')
    op.create_index(op.f('ix_panel_inbounds_id'), 'panel_inbounds', ['id'], unique=False)
    op.drop_column('panel_inbounds', 'stream_settings')
    op.drop_column('panel_inbounds', 'network')
    op.drop_column('panel_inbounds', 'client_stats')
    op.drop_column('panel_inbounds', 'tls')
    op.drop_column('panel_inbounds', 'sniffing')
    op.drop_column('panel_inbounds', 'remark')
    op.add_column('panel_server_migrations', sa.Column('migration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_panel_server_migrations_id'), 'panel_server_migrations', ['id'], unique=False)
    op.drop_column('panel_server_migrations', 'completed_at')
    op.drop_column('panel_server_migrations', 'migration_status')
    op.drop_column('panel_server_migrations', 'new_country_code')
    op.drop_column('panel_server_migrations', 'backup_file')
    op.drop_column('panel_server_migrations', 'new_geo_location')
    op.drop_column('panel_server_migrations', 'old_geo_location')
    op.drop_column('panel_server_migrations', 'old_country_code')
    op.drop_column('panel_server_migrations', 'started_at')
    op.drop_column('panel_server_migrations', 'reason')
    op.drop_column('panel_server_migrations', 'affected_clients_count')
    op.alter_column('panels', 'panel_type',
               existing_type=mysql.ENUM('3X-UI', 'MARZBAN', 'SANAEI', 'ALIREZA', 'VAXILU', 'XRAY', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_panels_id'), 'panels', ['id'], unique=False)
    op.drop_column('panels', 'current_clients')
    op.drop_column('panels', 'traffic_used')
    op.drop_column('panels', 'traffic_limit')
    op.drop_column('panels', 'max_clients')
    op.alter_column('payments', 'status',
               existing_type=mysql.ENUM('PENDING', 'VERIFIED', 'REJECTED', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               nullable=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_plan_categories_id'), 'plan_categories', ['id'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('settings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.alter_column('transactions', 'type',
               existing_type=mysql.ENUM('DEPOSIT', 'WITHDRAW', 'PURCHASE', 'REFUND', 'COMMISSION', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_index('telegram_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('telegram_id', 'users', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('DEPOSIT', 'WITHDRAW', 'PURCHASE', 'REFUND', 'COMMISSION', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_column('settings', 'updated_at')
    op.drop_column('settings', 'created_at')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plan_categories_id'), table_name='plan_categories')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'VERIFIED', 'REJECTED', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.add_column('panels', sa.Column('max_clients', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panels', sa.Column('traffic_limit', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('panels', sa.Column('traffic_used', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('panels', sa.Column('current_clients', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_panels_id'), table_name='panels')
    op.alter_column('panels', 'panel_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('3X-UI', 'MARZBAN', 'SANAEI', 'ALIREZA', 'VAXILU', 'XRAY', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.add_column('panel_server_migrations', sa.Column('affected_clients_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel_server_migrations', sa.Column('reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('started_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('old_country_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('old_geo_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('new_geo_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('backup_file', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('new_country_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('migration_status', mysql.ENUM('PENDING', 'COMPLETED', 'FAILED', collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('panel_server_migrations', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_panel_server_migrations_id'), table_name='panel_server_migrations')
    op.drop_column('panel_server_migrations', 'status')
    op.drop_column('panel_server_migrations', 'migration_date')
    op.add_column('panel_inbounds', sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('panel_inbounds', sa.Column('sniffing', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('panel_inbounds', sa.Column('tls', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('panel_inbounds', sa.Column('client_stats', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('panel_inbounds', sa.Column('network', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('panel_inbounds', sa.Column('stream_settings', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_index(op.f('ix_panel_inbounds_id'), table_name='panel_inbounds')
    op.create_index('panel_id', 'panel_inbounds', ['panel_id', 'inbound_id'], unique=False)
    op.alter_column('panel_inbounds', 'port',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('panel_inbounds', 'protocol',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('VMESS', 'VLESS', 'TROJAN', 'SHADOWSOCKS', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('panel_inbounds', 'tag',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.add_column('panel_health_checks', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('panel_health_checks', sa.Column('checked_at', mysql.DATETIME(), nullable=False))
    op.add_column('panel_health_checks', sa.Column('details', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_index(op.f('ix_panel_health_checks_id'), table_name='panel_health_checks')
    op.drop_column('panel_health_checks', 'disk_usage')
    op.drop_column('panel_health_checks', 'memory_usage')
    op.drop_column('panel_health_checks', 'cpu_usage')
    op.drop_column('panel_health_checks', 'error_message')
    op.drop_column('panel_health_checks', 'status_code')
    op.drop_column('panel_health_checks', 'is_healthy')
    op.drop_column('panel_health_checks', 'check_time')
    op.drop_index(op.f('ix_panel_domains_id'), table_name='panel_domains')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_index(op.f('ix_notification_channels_id'), table_name='notification_channels')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.alter_column('locations', 'migration_remark_pattern',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'{original}-M{count}'"))
    op.alter_column('locations', 'remark_pattern',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'{prefix}-{id}-{custom}'"))
    op.drop_column('locations', 'max_migrations_per_day')
    op.add_column('clients', sa.Column('qrcode_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('clients', sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('tls', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('security', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('clients', sa.Column('panel_inbound_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('network', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('clients', sa.Column('last_online', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_ibfk_7', 'clients', 'locations', ['original_location_id'], ['id'])
    op.create_foreign_key('clients_ibfk_3', 'clients', 'panel_inbounds', ['panel_inbound_id'], ['id'])
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.alter_column('clients', 'protocol',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('VMESS', 'VLESS', 'TROJAN', 'SHADOWSOCKS', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('clients', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('ACTIVE', 'EXPIRED', 'DISABLED', 'FROZEN', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.add_column('client_migrations', sa.Column('old_client_uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.add_column('client_migrations', sa.Column('new_client_uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.add_column('client_migrations', sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('client_migrations', sa.Column('migrated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('client_migrations', sa.Column('time_remaining_days', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('client_migrations', sa.Column('traffic_remaining', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_migrations', type_='foreignkey')
    op.drop_constraint(None, 'client_migrations', type_='foreignkey')
    op.drop_constraint(None, 'client_migrations', type_='foreignkey')
    op.drop_constraint(None, 'client_migrations', type_='foreignkey')
    op.drop_index(op.f('ix_client_migrations_id'), table_name='client_migrations')
    op.alter_column('client_migrations', 'reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.drop_column('client_migrations', 'created_at')
    op.drop_column('client_migrations', 'performed_by')
    op.drop_column('client_migrations', 'transferred_expiry')
    op.drop_column('client_migrations', 'transferred_traffic')
    op.drop_column('client_migrations', 'new_uuid')
    op.drop_column('client_migrations', 'old_uuid')
    op.drop_column('client_migrations', 'new_location_id')
    op.drop_column('client_migrations', 'old_location_id')
    op.drop_column('client_migrations', 'user_id')
    op.drop_index(op.f('ix_client_id_sequences_id'), table_name='client_id_sequences')
    op.drop_index(op.f('ix_bank_cards_id'), table_name='bank_cards')
    op.alter_column('bank_cards', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.create_table('discount_codes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('discount_type', mysql.ENUM('FIXED', 'PERCENTAGE'), nullable=True),
    sa.Column('discount_value', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='discount_codes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'discount_codes', ['code'], unique=False)
    op.drop_index(op.f('ix_panel_migration_map_id'), table_name='panel_migration_map')
    op.drop_table('panel_migration_map')
    op.drop_index(op.f('ix_client_migration_settings_id'), table_name='client_migration_settings')
    op.drop_table('client_migration_settings')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_table('backups')
    # ### end Alembic commands ###
