"""
Django settings for MoonVPN project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import sys
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()

# Look for .env file in multiple locations
env_files = [
    os.path.join(BASE_DIR, '.env'),
    os.path.join(BASE_DIR.parent, '.env'),
    os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env'),
    '/.env',
]

for env_file in env_files:
    if os.path.exists(env_file):
        environ.Env.read_env(env_file)
        print(f"Loaded environment from {env_file}")
        break
else:
    print("Warning: .env file not found, using default environment variables")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-nd(5!knb!j#v(ms3o!4g6v1zcy%#!)s#!b$%hpzxotn&(f=4j@')

# Field encryption key for django-encrypted-model-fields
FIELD_ENCRYPTION_KEY = env('FIELD_ENCRYPTION_KEY', default='npa4efNnv-Qx03T6Ce6ZQ8PiKA3sKBVlueOoD60HyBs=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# IP Whitelisting
BLACKLISTED_IPS = env.list('BLACKLISTED_IPS', default=[])
WHITELISTED_IPS = env.list('WHITELISTED_IPS', default=[])
ALLOWED_IPS = env.list('ALLOWED_IPS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'channels',  # For WebSocket support
    'model_utils',  # For model tracking
    'allauth',  # Django Allauth
    'allauth.account',  # For user accounts
    'allauth.socialaccount',  # For social accounts
    'encrypted_model_fields',  # For encrypted fields
    'drf_yasg',
    'debug_toolbar',
    'django_redis',
    # Local apps
    'main',
    'chat',  # Live chat app
    'v2ray',  # V2Ray management app
    'payments',  # Payment processing app
    'api',  # API endpoints app
    'telegrambot',  # Telegram bot app
    'points',  # Points system app
    'vpn',  # New VPN module
    'utils',  # Add utils app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='moonvpn'),
        'USER': env('DB_USER', default='moonvpn'),
        'PASSWORD': env('DB_PASSWORD', default='moonvpn'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}

# Custom User Model
AUTH_USER_MODEL = 'main.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing Settings
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fa'  # Default to Persian

TIME_ZONE = 'Asia/Tehran'  # Iran timezone

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGES = [
    ('fa', 'Persian'),
    ('en', 'English'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = []
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{env('REDIS_HOST', default='localhost')}:{env('REDIS_PORT', default=6379)}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Cache time to live is 15 minutes
CACHE_TTL = 60 * 15

# Session settings
# Use Redis for sessions in production, but use database for tests
if 'test' in sys.argv:
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
else:
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

# Security Middleware Settings - Only in production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
else:
    # Disable security features in development
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# CSP Settings
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # Required for Material-UI
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")  # Required for React
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'", "https:")
CSP_UPGRADE_INSECURE_REQUESTS = not DEBUG

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Celery Settings
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')

# Telegram Bot Settings
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_WEBHOOK_URL = env('TELEGRAM_WEBHOOK_URL', default='')
TELEGRAM_ADMIN_GROUP_ID = env('TELEGRAM_ADMIN_GROUP_ID', default='')

# Payment Settings
ZARINPAL_MERCHANT_ID = env('ZARINPAL_MERCHANT_ID', default='')
ZARINPAL_SANDBOX = env.bool('ZARINPAL_SANDBOX', default=True)
ZARINPAL_CALLBACK_URL = env('ZARINPAL_CALLBACK_URL', default='http://localhost:8000/api/payment/callback/')

# Frontend URLs for payment redirection
PAYMENT_SUCCESS_URL = env('PAYMENT_SUCCESS_URL', default='http://localhost:3000/payment/success')
PAYMENT_FAILURE_URL = env('PAYMENT_FAILURE_URL', default='http://localhost:3000/payment/failure')

# Points System Settings
POINTS_PER_PURCHASE = env.int('POINTS_PER_PURCHASE', default=10)
POINTS_PER_REFERRAL = env.int('POINTS_PER_REFERRAL', default=50)
POINTS_EXPIRY_DAYS = env.int('POINTS_EXPIRY_DAYS', default=365)

# Live Chat Settings
LIVE_CHAT_ENABLED = env.bool('LIVE_CHAT_ENABLED', default=True)
MAX_CHAT_SESSIONS = env.int('MAX_CHAT_SESSIONS', default=5)
CHAT_TIMEOUT_MINUTES = env.int('CHAT_TIMEOUT_MINUTES', default=30)

# Channels Settings (for WebSocket)
ASGI_APPLICATION = 'config.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(env('REDIS_HOST', default='localhost'), env.int('REDIS_PORT', default=6379))],
        },
    },
}

# Debug Toolbar Settings
if DEBUG:
    INTERNAL_IPS = [
        '127.0.0.1',
    ]

# OCR Settings
TESSERACT_CMD_PATH = env('TESSERACT_CMD_PATH', default='tesseract')
OCR_KERNEL_SIZE = (1, 1)
OCR_THRESHOLD_BLOCK_SIZE = 11
OCR_THRESHOLD_C = 2
OCR_MIN_CONFIDENCE = 50  # Minimum confidence percentage for OCR results

# Card Payment Settings
CARD_PAYMENT_VERIFICATION_TIMEOUT_MINUTES = env.int('CARD_PAYMENT_VERIFICATION_TIMEOUT_MINUTES', default=30)
CARD_PAYMENT_NUMBER = env('CARD_PAYMENT_NUMBER', default='')
CARD_PAYMENT_HOLDER = env('CARD_PAYMENT_HOLDER', default='')
CARD_PAYMENT_BANK = env('CARD_PAYMENT_BANK', default='')
ADMIN_NOTIFICATION_ENABLED = env.bool('ADMIN_NOTIFICATION_ENABLED', default=True)

# Media settings for receipt images
RECEIPTS_UPLOAD_PATH = 'receipts/%Y/%m/%d/'

# Site ID for django.contrib.sites
SITE_ID = 1

# Telegram bot settings
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_WEBHOOK_URL = env('TELEGRAM_WEBHOOK_URL', default='')
ADMIN_USER_IDS = env.list('ADMIN_USER_IDS', default=[])

# VPN settings
VPN_MOCK_DATA = env.bool('VPN_MOCK_DATA', default=False)
VPN_DEFAULT_PROTOCOL = env('VPN_DEFAULT_PROTOCOL', default='vmess')
VPN_DEFAULT_TRAFFIC_LIMIT_GB = int(env('VPN_DEFAULT_TRAFFIC_LIMIT_GB', default=50))
VPN_DEFAULT_EXPIRE_DAYS = int(env('VPN_DEFAULT_EXPIRE_DAYS', default=30))

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Comment out the file handler for now as it's causing issues
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'logging.FileHandler',
        #     'filename': os.path.join(BASE_DIR, '../logs/django.log'),
        #     'formatter': 'verbose',
        # },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],  # Removed 'file'
            'level': 'INFO',
            'propagate': True,
        },
        'vpn': {
            'handlers': ['console'],  # Removed 'file'
            'level': 'INFO',
            'propagate': False,
        },
    },
}
